name: Build Website
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Site
        run: npm run build

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.number }}
          path: dist
